server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # discovery locator enabled, para permitir que el gateway genere
          # rutas automaticamente
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # El gateway se conecta al registry